title: vireak comino
author: sath sovireak
email: sathsovireak18@kit.edu.kh
description: > # this means to ignore newlines until "baseurl:"
  This website will help you to improve your knowledge.Please enjoy my website.

# social links
facebook_username: vireak comino
github_username:  sath sovireak

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
